spring:
  application:
    name: quizapp

  datasource:
    url: jdbc:postgresql://localhost:5432/quiz_app
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true